/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Sun Jul 16 02:54:24 2017. */

#ifndef PB_GG_PROTOBUF_GG_PB_H_INCLUDED
#define PB_GG_PROTOBUF_GG_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _gg_protobuf_InFile_Type {
    gg_protobuf_InFile_Type_FILE = 0,
    gg_protobuf_InFile_Type_DUMMY_DIRECTORY = 1
} gg_protobuf_InFile_Type;
#define _gg_protobuf_InFile_Type_MIN gg_protobuf_InFile_Type_FILE
#define _gg_protobuf_InFile_Type_MAX gg_protobuf_InFile_Type_DUMMY_DIRECTORY
#define _gg_protobuf_InFile_Type_ARRAYSIZE ((gg_protobuf_InFile_Type)(gg_protobuf_InFile_Type_DUMMY_DIRECTORY+1))

/* Struct definitions */
typedef struct _gg_protobuf_Function {
    pb_callback_t exe;
    pb_callback_t args;
    pb_callback_t hash;
/* @@protoc_insertion_point(struct:gg_protobuf_Function) */
} gg_protobuf_Function;

typedef struct _gg_protobuf_InFile {
    pb_callback_t filename;
    pb_callback_t hash;
    uint32_t order;
    uint64_t size;
    gg_protobuf_InFile_Type type;
/* @@protoc_insertion_point(struct:gg_protobuf_InFile) */
} gg_protobuf_InFile;

typedef struct _gg_protobuf_Thunk {
    gg_protobuf_Function function;
    pb_callback_t infiles;
    pb_callback_t outfile;
/* @@protoc_insertion_point(struct:gg_protobuf_Thunk) */
} gg_protobuf_Thunk;

/* Default values for struct fields */

/* Initializer values for message structs */
#define gg_protobuf_Function_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_InFile_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, (gg_protobuf_InFile_Type)0}
#define gg_protobuf_Thunk_init_default           {gg_protobuf_Function_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_Function_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_InFile_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, (gg_protobuf_InFile_Type)0}
#define gg_protobuf_Thunk_init_zero              {gg_protobuf_Function_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define gg_protobuf_Function_exe_tag             1
#define gg_protobuf_Function_args_tag            2
#define gg_protobuf_Function_hash_tag            3
#define gg_protobuf_InFile_filename_tag          1
#define gg_protobuf_InFile_hash_tag              2
#define gg_protobuf_InFile_order_tag             3
#define gg_protobuf_InFile_size_tag              4
#define gg_protobuf_InFile_type_tag              5
#define gg_protobuf_Thunk_function_tag           1
#define gg_protobuf_Thunk_infiles_tag            2
#define gg_protobuf_Thunk_outfile_tag            3

/* Struct field encoding specification for nanopb */
extern const pb_field_t gg_protobuf_Function_fields[4];
extern const pb_field_t gg_protobuf_InFile_fields[6];
extern const pb_field_t gg_protobuf_Thunk_fields[4];

/* Maximum encoded size of messages (where known) */
/* gg_protobuf_Function_size depends on runtime parameters */
/* gg_protobuf_InFile_size depends on runtime parameters */
/* gg_protobuf_Thunk_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
