/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Mar 19 15:18:44 2018. */

#ifndef PB_GG_PROTOBUF_GG_PB_H_INCLUDED
#define PB_GG_PROTOBUF_GG_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _gg_protobuf_ExecutionRequest {
    pb_callback_t thunks;
    pb_callback_t storage_backend;
/* @@protoc_insertion_point(struct:gg_protobuf_ExecutionRequest) */
} gg_protobuf_ExecutionRequest;

typedef struct _gg_protobuf_Function {
    pb_callback_t hash;
    pb_callback_t args;
    pb_callback_t envars;
/* @@protoc_insertion_point(struct:gg_protobuf_Function) */
} gg_protobuf_Function;

typedef struct _gg_protobuf_RequestItem {
    pb_callback_t hash;
    pb_callback_t data;
    pb_callback_t outputs;
/* @@protoc_insertion_point(struct:gg_protobuf_RequestItem) */
} gg_protobuf_RequestItem;

typedef struct _gg_protobuf_ResponseItem {
    pb_callback_t thunk_hash;
    pb_callback_t outputs;
/* @@protoc_insertion_point(struct:gg_protobuf_ResponseItem) */
} gg_protobuf_ResponseItem;

typedef struct _gg_protobuf_ExecutionResponse {
    pb_callback_t executed_thunks;
    uint32_t return_code;
    pb_callback_t output;
/* @@protoc_insertion_point(struct:gg_protobuf_ExecutionResponse) */
} gg_protobuf_ExecutionResponse;

typedef struct _gg_protobuf_LambdaInFile {
    pb_callback_t hash;
    bool executable;
    uint64_t size;
/* @@protoc_insertion_point(struct:gg_protobuf_LambdaInFile) */
} gg_protobuf_LambdaInFile;

typedef struct _gg_protobuf_OutputItem {
    pb_callback_t tag;
    pb_callback_t hash;
    uint32_t size;
    bool executable;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:gg_protobuf_OutputItem) */
} gg_protobuf_OutputItem;

typedef struct _gg_protobuf_Thunk {
    gg_protobuf_Function function;
    pb_callback_t values;
    pb_callback_t thunks;
    pb_callback_t executables;
    pb_callback_t outputs;
/* @@protoc_insertion_point(struct:gg_protobuf_Thunk) */
} gg_protobuf_Thunk;

/* Default values for struct fields */

/* Initializer values for message structs */
#define gg_protobuf_Function_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_Thunk_init_default           {gg_protobuf_Function_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_LambdaInFile_init_default    {{{NULL}, NULL}, 0, 0}
#define gg_protobuf_RequestItem_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_ExecutionRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_OutputItem_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define gg_protobuf_ResponseItem_init_default    {{{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_ExecutionResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gg_protobuf_Function_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_Thunk_init_zero              {gg_protobuf_Function_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_LambdaInFile_init_zero       {{{NULL}, NULL}, 0, 0}
#define gg_protobuf_RequestItem_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_ExecutionRequest_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_OutputItem_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define gg_protobuf_ResponseItem_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}}
#define gg_protobuf_ExecutionResponse_init_zero  {{{NULL}, NULL}, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define gg_protobuf_ExecutionRequest_thunks_tag  1
#define gg_protobuf_ExecutionRequest_storage_backend_tag 2
#define gg_protobuf_Function_hash_tag            1
#define gg_protobuf_Function_args_tag            2
#define gg_protobuf_Function_envars_tag          3
#define gg_protobuf_RequestItem_hash_tag         1
#define gg_protobuf_RequestItem_data_tag         2
#define gg_protobuf_RequestItem_outputs_tag      3
#define gg_protobuf_ResponseItem_thunk_hash_tag  1
#define gg_protobuf_ResponseItem_outputs_tag     2
#define gg_protobuf_ExecutionResponse_executed_thunks_tag 1
#define gg_protobuf_ExecutionResponse_return_code_tag 2
#define gg_protobuf_ExecutionResponse_output_tag 3
#define gg_protobuf_LambdaInFile_hash_tag        1
#define gg_protobuf_LambdaInFile_size_tag        3
#define gg_protobuf_LambdaInFile_executable_tag  2
#define gg_protobuf_OutputItem_tag_tag           1
#define gg_protobuf_OutputItem_hash_tag          2
#define gg_protobuf_OutputItem_size_tag          3
#define gg_protobuf_OutputItem_executable_tag    4
#define gg_protobuf_OutputItem_data_tag          5
#define gg_protobuf_Thunk_function_tag           1
#define gg_protobuf_Thunk_values_tag             2
#define gg_protobuf_Thunk_thunks_tag             3
#define gg_protobuf_Thunk_executables_tag        4
#define gg_protobuf_Thunk_outputs_tag            5

/* Struct field encoding specification for nanopb */
extern const pb_field_t gg_protobuf_Function_fields[4];
extern const pb_field_t gg_protobuf_Thunk_fields[6];
extern const pb_field_t gg_protobuf_LambdaInFile_fields[4];
extern const pb_field_t gg_protobuf_RequestItem_fields[4];
extern const pb_field_t gg_protobuf_ExecutionRequest_fields[3];
extern const pb_field_t gg_protobuf_OutputItem_fields[6];
extern const pb_field_t gg_protobuf_ResponseItem_fields[3];
extern const pb_field_t gg_protobuf_ExecutionResponse_fields[4];

/* Maximum encoded size of messages (where known) */
/* gg_protobuf_Function_size depends on runtime parameters */
/* gg_protobuf_Thunk_size depends on runtime parameters */
/* gg_protobuf_LambdaInFile_size depends on runtime parameters */
/* gg_protobuf_RequestItem_size depends on runtime parameters */
/* gg_protobuf_ExecutionRequest_size depends on runtime parameters */
/* gg_protobuf_OutputItem_size depends on runtime parameters */
/* gg_protobuf_ResponseItem_size depends on runtime parameters */
/* gg_protobuf_ExecutionResponse_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
