/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Mar 14 16:11:05 2018. */

#include "gg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t gg_protobuf_Function_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gg_protobuf_Function, hash, hash, 0),
    PB_FIELD(  2, STRING  , REPEATED, CALLBACK, OTHER, gg_protobuf_Function, args, hash, 0),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, gg_protobuf_Function, envars, args, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_Thunk_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, gg_protobuf_Thunk, function, function, &gg_protobuf_Function_fields),
    PB_FIELD(  2, STRING  , REPEATED, CALLBACK, OTHER, gg_protobuf_Thunk, data, function, 0),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, gg_protobuf_Thunk, executables, data, 0),
    PB_FIELD(  4, STRING  , REPEATED, CALLBACK, OTHER, gg_protobuf_Thunk, outputs, executables, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_LambdaInFile_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gg_protobuf_LambdaInFile, hash, hash, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, gg_protobuf_LambdaInFile, executable, hash, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, gg_protobuf_LambdaInFile, size, executable, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_RequestItem_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gg_protobuf_RequestItem, thunk_hash, thunk_hash, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_RequestItem, thunk_data, thunk_hash, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_ExecutionRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, gg_protobuf_ExecutionRequest, thunks, thunks, &gg_protobuf_RequestItem_fields),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_ExecutionRequest, storage_backend, thunks, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_ResponseItem_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gg_protobuf_ResponseItem, thunk_hash, thunk_hash, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_ResponseItem, output_hash, thunk_hash, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, gg_protobuf_ResponseItem, output_size, output_hash, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, gg_protobuf_ResponseItem, executable_output, output_size, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_ExecutionResponse_fields[4] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, gg_protobuf_ExecutionResponse, executed_thunks, executed_thunks, &gg_protobuf_ResponseItem_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, gg_protobuf_ExecutionResponse, return_code, executed_thunks, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_ExecutionResponse, output, return_code, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(gg_protobuf_Thunk, function) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_gg_protobuf_Function_gg_protobuf_Thunk_gg_protobuf_LambdaInFile_gg_protobuf_RequestItem_gg_protobuf_ExecutionRequest_gg_protobuf_ResponseItem_gg_protobuf_ExecutionResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(gg_protobuf_Thunk, function) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_gg_protobuf_Function_gg_protobuf_Thunk_gg_protobuf_LambdaInFile_gg_protobuf_RequestItem_gg_protobuf_ExecutionRequest_gg_protobuf_ResponseItem_gg_protobuf_ExecutionResponse)
#endif


/* @@protoc_insertion_point(eof) */
