/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Jul 16 02:54:24 2017. */

#include "gg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t gg_protobuf_Function_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gg_protobuf_Function, exe, exe, 0),
    PB_FIELD(  2, STRING  , REPEATED, CALLBACK, OTHER, gg_protobuf_Function, args, exe, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_Function, hash, args, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_InFile_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, gg_protobuf_InFile, filename, filename, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_InFile, hash, filename, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, gg_protobuf_InFile, order, hash, 0),
    PB_FIELD(  4, UINT64  , SINGULAR, STATIC  , OTHER, gg_protobuf_InFile, size, order, 0),
    PB_FIELD(  5, UENUM   , SINGULAR, STATIC  , OTHER, gg_protobuf_InFile, type, size, 0),
    PB_LAST_FIELD
};

const pb_field_t gg_protobuf_Thunk_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, gg_protobuf_Thunk, function, function, &gg_protobuf_Function_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, gg_protobuf_Thunk, infiles, function, &gg_protobuf_InFile_fields),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, gg_protobuf_Thunk, outfile, infiles, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(gg_protobuf_Thunk, function) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_gg_protobuf_Function_gg_protobuf_InFile_gg_protobuf_Thunk)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(gg_protobuf_Thunk, function) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_gg_protobuf_Function_gg_protobuf_InFile_gg_protobuf_Thunk)
#endif


/* @@protoc_insertion_point(eof) */
